[package]
name = "htmx-convex-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
dotenvy = "0.15.7"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
tera = "1.20.0"
